[package]
name = "starship-manager-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
toml_edit = { workspace = true }
starship-manager-core = { workspace = true }
starship-manager-preview = { workspace = true }
starship-manager-install = { workspace = true }
